from collections import deque
stack = deque()
stack.append(1)
stack.append(2)
stack.append(5)
print(stack)
print(stack.pop())
print(stack)

queue = deque()
queue.appendleft(1)
queue.appendleft(5)
queue.appendleft(10)
print(queue)
print(queue.pop())
print(queue)
